### ISSUE TITLE
Função deleteMessage não está funcionando.

### ISSUE THREAD

**Issue by jtapeg** [wppconnect-team/wppconnect#1978]
Função de deletar mensagem não está funcionando, retorna sempre true.

- **WPPConnect version(s):** 1.28.3
- **WA-JS version(s):** 2.28.0
- **Browser:** Chromium
- **OS:** Linux ubuntu
- **Node version:** Node 18
- **WhatsApp version:** 2.2353.0
- **MultiDevice (BETA):** yes

**Comment by Guils1** [comment]
Tenho tido o mesmo problema

**Comment by vitortoigo** [comment]
Aqui a mesma coisa, retorna true mas não delete a mensagem.

**Comment by icleitoncosta** [comment]
Por favor, façam um teste, por gentileza.
Atualizem a versão de vocês para a ultima do wa-js, exemplo:

English:
Please, kindly perform a test.
Update your version to the latest of wa-js, for example:

`yarn add @wppconnect/wa-js@latest`
or
`npm install @wppconnect/wa-js@latest`

Eu havia feito alguns testes e o bug só resolvia com a ultima versão atualizada, mas como só estou testando localmente, quero que mais pessoas façam o teste para validar, ai só lanço uma release com outras correções que essa já será corrigida.

English:
I had conducted some tests, and the bug was only resolved with the latest updated version. However, since I am only testing locally, I want more people to perform the test to validate it. Then, I will release a version with other fixes, and this one will already be corrected.

**Comment by Guils1** [comment]
A correção, infelizmente não funcionou. Foi realizado teste no meu local com a última versão e ainda continua com o mesmo problema, retornando um valor boolean como true sem a ação ser refletida no whatsapp.

**Comment by icleitoncosta** [comment]
> A correção, infelizmente não funcionou. Foi realizado teste no meu local com a última versão e ainda continua com o mesmo problema, retornando um valor boolean como true sem a ação ser refletida no whatsapp.
> 
> 

Qual a versão no package.json?

**Comment by Guils1** [comment]
2.28.1

**Comment by Guils1** [comment]
`
"@wppconnect-team/wppconnect": "^1.28.3",
"@wppconnect/wa-js": "^2.28.1",
`

**Comment by vitortoigo** [comment]
Alguem conseguiu resolver esse problema?

**Comment by Guils1** [comment]
Ainda não 😮‍💨

**Comment by vitortoigo** [comment]
> Ainda não 😮‍💨

Alterando a versão do WhatsApp Web nas configurações de criação do bot normalizou.
Utilizei a ultima versão (2.2402.5).

**Comment by Guils1** [comment]
Galera, alterando a versão do whatsapp web funcionou pra mim também, mas notei que o método só funciona se o onlyLocal? for true

**Comment by jtapeg** [comment]
Aqui esta funcionando normal tanto com onlyLocal true ou false.
