### ISSUE TITLE
sendSeen não está marcando mensagens no celular

### ISSUE THREAD

**Issue by dionatanfmsilva** [wppconnect-team/wppconnect#786]
## Description

sendSeen é chamado e executado com sucesso porém no celular as mensagens continuam não marcadas

## Environment

- **Wppconnect version(s):** [1.10.3, 1.11.0, 1.11.1, 1.12.0]
- **Browser:** [Chrome 96, Chrome 97]
- **OS:** [Ubuntu 21.04, Windows 10]
- **Node version:** [Node 14.18.2, Node 14.5.5]
- **WhatsApp version:** [2.2144.11]
- **MultiDevice (BETA):** no

## Steps to Reproduce

1. Enviar uma ou mais mensagens de qualquer numero para o numero conectado
2. Utilizar a função sendSeen para marcar as mensagens
3. Realizar a ação pelo menos 2x, pois as vezes a primeira vez funciona

## Log Output

```
{
    "wid": {
        "server": "c.us",
        "user": "5543XXXXXXXX",
        "_serialized": "5543XXXXXXXX@c.us"
    },
    "unreadCount": 3
}
```

**Comment by alanvictorjp** [comment]
Acontece o mesmo comigo, antigamente eu usava o UnreadMessages para ver mensagens não lidas, mas agora está diferente, mesmo a lib enviando mensagens, ainda fica a bolinha verde la, como mensagem não lida, dai comecei a usar o sendseen, mas nao deu muito certo porque as vezes nao funciona.

**Comment by edgardmessias** [comment]
Próxima versão do WA-JS vai estar resolvido isso

**Comment by gekkedev** [comment]
I got this problem as well, could we reopen it? I run
```js
client.onMessage(async (message) => {
  await client.sendSeen(message.chatId)
})
```
because the documentation example uses the serialized user string: https://wppconnect.io/docs/tutorial/basics/basic-functions#sendseen
The status never changes to seen unless I send a reply or a second message. Example:

1. first message
   - isn't seen
2. second message
   - messages 1, 2 are seen
2. third message
   - messages 1, 2 are seen
   - 3 isn't seen
2. fourth message
   - messages 1, 2, 3, and 4 are seen
